export const TOGGLE_SEARCH_UI = 'TOGGLE_SEARCH_UI';
export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_SUCCESSFUL = 'SEARCH_SUCCESSFUL';
export const SEARCH_FAILED = 'SEARCH_FAILED';
